

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "@/components/layout/NavBar";
import AddHotelForm from "@/components/hotel/AddHotelForm";
import Hotel from "./hotel/[hotelId]/page";
import Container from "@/components/ui/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider  publishableKey={'pk_test_bG92aW5nLXRhcGlyLTkyLmNsZXJrLmFjY291bnRzLmRldiQ'}>   
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >

        
      <main className="flex flex-col min-h-screen bg-secondary">
       <NavBar/> 
       
       <section  className="flex-grow">
        <Container>
          {children}
        </Container>
        
       </section>
      </main>
      </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
